# Generated by Django 6.0.1 on 2026-03-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('edad', models.IntegerField()),
                ('carrera', models.CharField(max_length=100)),
                ('promedio', models.FloatField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='estudiantes/')),
                ('foto_binaria', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
