# Generated by Django 6.0.1 on 2026-03-10 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='estudiantes/'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='foto_binaria',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
